import { Product } from "../../../types/product/ProductTypes";

const electronicsCategory = {
  id: 1,
  name: "Electronics",
  categoryId: "electronics",
  level: 1,
  parentCategory: null as any, // cheating for top-level
};
electronicsCategory.parentCategory = electronicsCategory;

const fashionCategory = {
  id: 2,
  name: "Fashion",
  categoryId: "fashion",
  level: 1,
  parentCategory: null as any,
};
fashionCategory.parentCategory = fashionCategory;

const homeOfficeCategory = {
  id: 4,
  name: "Home & Office",
  categoryId: "home-office",
  level: 1,
  parentCategory: null as any,
};
homeOfficeCategory.parentCategory = homeOfficeCategory;

const fitnessCategory = {
  id: 5,
  name: "Fitness",
  categoryId: "fitness",
  level: 1,
  parentCategory: null as any,
};
fitnessCategory.parentCategory = fitnessCategory;

const photographyCategory = {
  id: 6,
  name: "Photography",
  categoryId: "photography",
  level: 1,
  parentCategory: null as any,
};
photographyCategory.parentCategory = photographyCategory;

const kitchenCategory = {
  id: 7,
  name: "Kitchen",
  categoryId: "kitchen",
  level: 1,
  parentCategory: null as any,
};
kitchenCategory.parentCategory = kitchenCategory;

export const dummyProducts: Product[] = [
  {
    id: 1,
    name: "QuantumX Pro Gaming Mouse",
    title: "QuantumX Pro Gaming Mouse",
    description:
      "Experience unparalleled precision and speed with the QuantumX Pro Gaming Mouse. Featuring a 26,000 DPI sensor, light-speed wireless technology, and 8 programmable buttons. Ergonomically designed for marathon gaming sessions.",
    sellingPrice: 79.99,
    mrpPrice: 99.99,
    discountPercentage: 20,
    quantity: 50,
    colour: "Black",
    availableSizes: [],
    images: [
      "https://t4.ftcdn.net/jpg/06/25/07/31/360_F_625073135_IixKG2q7WLZUhuuA5nWnSmUB3PP0lCBL.jpg",
    ],
    category: electronicsCategory,
    brand: "QuantumX",
    reviews: [],
    numbsRatings: 120,
    createdAt: new Date(),
    sizeType: "standard",
    viewCount: 1500,
  },
  {
    id: 2,
    name: "AetherFlow Noise-Cancelling Headphones",
    title: "AetherFlow Noise-Cancelling Headphones",
    description:
      "Immerse yourself in pure audio with AetherFlow headphones. Featuring industry-leading noise cancellation, 30-hour battery life, and crystal-clear call quality. Crafted with premium materials for ultimate comfort.",
    sellingPrice: 349.99,
    mrpPrice: 399.99,
    discountPercentage: 12.5,
    quantity: 30,
    colour: "Graphite",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=800&auto=format&fit=crop",
    ],
    category: electronicsCategory,
    brand: "AetherFlow",
    reviews: [],
    numbsRatings: 250,
    createdAt: new Date(),
    sizeType: "standard",
    viewCount: 2500,
  },
  {
    id: 3,
    name: "Nomad's Canvas Adventure Backpack",
    title: "Nomad's Canvas Adventure Backpack",
    description:
      "Built for the modern explorer, the Nomad's Canvas backpack is durable, water-resistant, and stylish. With a 30L capacity, dedicated laptop sleeve, and multiple compartments, it's your perfect travel companion.",
    sellingPrice: 120.0,
    mrpPrice: 150.0,
    discountPercentage: 20,
    quantity: 75,
    colour: "Forest Green",
    availableSizes: [],
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7jTzuyuKQAKyP_wH1Nb90ZsC7wVMWIII8eFsF2QTpWos-ymZh6orJY32zWIapsVgGcOSALKpYdNQhlDml11s9VUXkhTbXvSl8ExJlO5io",
    ],
    category: fashionCategory,
    brand: "Wanderlust Gear",
    reviews: [],
    numbsRatings: 95,
    createdAt: new Date(),
    sizeType: "liters",
    viewCount: 1200,
  },
  {
    id: 4,
    name: "Zenith Smartwatch Series 5",
    title: "Zenith Smartwatch Series 5",
    description:
      "Stay connected and track your fitness with the Zenith Smartwatch. Features a vibrant AMOLED display, GPS, heart rate monitoring, and a wide range of smart notifications. All-day battery life.",
    sellingPrice: 229.0,
    mrpPrice: 279.0,
    discountPercentage: 18,
    quantity: 60,
    colour: "Midnight Blue",
    availableSizes: [],
    images: [
      "https://rukminim3.flixcart.com/image/850/1000/xif0q/smartwatch/t/7/h/-original-imagyxv3ff7d7hz9.jpeg?q=90&crop=false",
    ],
    category: electronicsCategory,
    brand: "Zenith",
    reviews: [],
    numbsRatings: 180,
    createdAt: new Date(),
    sizeType: "mm",
    viewCount: 3500,
  },
  {
    id: 5,
    name: "AeroPress Go Portable Coffee Maker",
    title: "AeroPress Go Portable Coffee Maker",
    description:
      "Brew delicious, grit-free coffee anywhere with the AeroPress Go. Compact, lightweight, and durable, it makes a perfect cup in under a minute. Ideal for travel, camping, or the office.",
    sellingPrice: 39.95,
    mrpPrice: 45.0,
    discountPercentage: 11,
    quantity: 150,
    colour: "Translucent Grey",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1461988091159-192b6df7054f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y29mZmVlJTIwbWFjaGluZXxlbnwwfHwwfHx8MA%3D%3D",
    ],
    category: kitchenCategory,
    brand: "AeroPress",
    reviews: [],
    numbsRatings: 320,
    createdAt: new Date(),
    sizeType: "standard",
    viewCount: 5000,
  },
  {
    id: 6,
    name: "Pro-Grip Yoga Mat (72-Inch)",
    title: "Pro-Grip Yoga Mat (72-Inch)",
    description:
      "Find your balance with the Pro-Grip Yoga Mat. Made from eco-friendly, non-slip material, it provides superior cushioning and stability for your practice. Lightweight and easy to clean.",
    sellingPrice: 45.5,
    mrpPrice: 60.0,
    discountPercentage: 24,
    quantity: 100,
    colour: "Teal",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eW9nYSUyMG1hdHxlbnwwfHwwfHx8MA%3D%3D",
    ],
    category: fitnessCategory,
    brand: "FlowState",
    reviews: [],
    numbsRatings: 78,
    createdAt: new Date(),
    sizeType: "inches",
    viewCount: 800,
  },
  {
    id: 7,
    name: "Lumina 4K Webcam",
    title: "Lumina 4K Webcam",
    description:
      "Look your best on video calls with the Lumina 4K Webcam. Featuring an ultra-HD sensor, AI-powered auto-framing, and dual noise-reducing microphones for crystal-clear communication.",
    sellingPrice: 129.99,
    mrpPrice: 159.99,
    discountPercentage: 18.75,
    quantity: 45,
    colour: "Silver",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1636569826709-8e07f6104992?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8d2ViY2FtfGVufDB8fDB8fHww",
    ],
    category: homeOfficeCategory,
    brand: "Lumina",
    reviews: [],
    numbsRatings: 150,
    createdAt: new Date(),
    sizeType: "standard",
    viewCount: 1800,
  },
  {
    id: 8,
    name: "Chef's Precision 8-inch Knife",
    title: "Chef's Precision 8-inch Knife",
    description:
      "Crafted from high-carbon German steel, this chef's knife offers exceptional sharpness, durability, and balance. The ergonomic handle ensures a comfortable and secure grip for all your kitchen tasks.",
    sellingPrice: 89.0,
    mrpPrice: 120.0,
    discountPercentage: 26,
    quantity: 80,
    colour: "Steel",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1622810917846-719511f8e618?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8OCUyMGluY2glMjBrbmlmZXxlbnwwfHwwfHx8MA%3D%3D",
    ],
    category: kitchenCategory,
    brand: "BladeMaster",
    reviews: [],
    numbsRatings: 210,
    createdAt: new Date(),
    sizeType: "inches",
    viewCount: 1400,
  },
  {
    id: 9,
    name: "Vortex Power Blender",
    title: "Vortex Power Blender",
    description:
      "Unleash your culinary creativity with the Vortex Power Blender. Its 1500-watt motor can handle anything from smoothies to hot soups. Features variable speed control and a self-cleaning function.",
    sellingPrice: 199.99,
    mrpPrice: 249.99,
    discountPercentage: 20,
    quantity: 40,
    colour: "Obsidian",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1585515320310-259814833e62?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmxlbmRlcnxlbnwwfHwwfHx8MA%3D%3D",
    ],
    category: kitchenCategory,
    brand: "Vortex",
    reviews: [],
    numbsRatings: 135,
    createdAt: new Date(),
    sizeType: "standard",
    viewCount: 2200,
  },
  {
    id: 10,
    name: "CarbonFlex Pro Tripod",
    title: "CarbonFlex Pro Tripod",
    description:
      "Lightweight yet incredibly stable, the CarbonFlex Pro Tripod is a photographer's best friend. Made from 8-layer carbon fiber, it supports up to 33 lbs and extends to 65 inches.",
    sellingPrice: 259.0,
    mrpPrice: 329.0,
    discountPercentage: 21,
    quantity: 35,
    colour: "Carbon Black",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1576299090369-9067e4adca28?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dHJpcG9kfGVufDB8fDB8fHww",
    ],
    category: photographyCategory,
    brand: "AxisGrip",
    reviews: [],
    numbsRatings: 65,
    createdAt: new Date(),
    sizeType: "inches",
    viewCount: 950,
  },
  {
    id: 11,
    name: "TerraGlow Smart LED Desk Lamp",
    title: "TerraGlow Smart LED Desk Lamp",
    description:
      "Illuminate your workspace with the TerraGlow Smart Lamp. Offers adjustable color temperature and brightness, a wireless charging pad, and smart control via app or voice assistant.",
    sellingPrice: 65.0,
    mrpPrice: 85.0,
    discountPercentage: 23.5,
    quantity: 90,
    colour: "White",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1621447980929-6638614633c8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVzayUyMGxhbXB8ZW58MHx8MHx8fDA%3D",
    ],
    category: homeOfficeCategory,
    brand: "TerraGlow",
    reviews: [],
    numbsRatings: 110,
    createdAt: new Date(),
    sizeType: "standard",
    viewCount: 1100,
  },
  {
    id: 12,
    name: "HydroFlow Insulated Water Bottle (32 oz)",
    title: "HydroFlow Insulated Water Bottle (32 oz)",
    description:
      "Keep your drinks cold for 24 hours or hot for 12 with the HydroFlow bottle. Made from pro-grade stainless steel with a leak-proof lid and a durable, powder-coated finish.",
    sellingPrice: 29.95,
    mrpPrice: 35.0,
    discountPercentage: 14.5,
    quantity: 200,
    colour: "Arctic White",
    availableSizes: [],
    images: [
      "https://images.unsplash.com/photo-1675601263169-7a2c8f22f27d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGh5ZHJvZmxvd3xlbnwwfHwwfHx8MA%3D%3D",
    ],
    category: fitnessCategory,
    brand: "HydroFlow",
    reviews: [],
    numbsRatings: 450,
    createdAt: new Date(),
    sizeType: "oz",
    viewCount: 6000,
  },
];
